# Generated by Django 4.2 on 2023-05-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, default='', max_length=256)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/%Y/%m/%d')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_profile.profile', verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'Profile image',
                'verbose_name_plural': 'Profile images',
                'ordering': ['pk'],
            },
        ),
    ]
