# Generated by Django 4.2 on 2023-05-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_rename_review_reviews'),
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('deliveryType', models.CharField(default='Обычная', max_length=128, verbose_name='тип доставки')),
                ('paymentType', models.CharField(default='Онлайн картой', max_length=128, verbose_name='тип оплаты')),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма заказа')),
                ('status', models.CharField(default='Ожидает оплаты', max_length=128, verbose_name='статус')),
                ('city', models.CharField(default='', max_length=256, verbose_name='город')),
                ('address', models.CharField(default='', max_length=256, verbose_name='адрес')),
                ('products', models.ManyToManyField(related_name='orders', to='catalog.product', verbose_name='продукты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_profile.profile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
