# Generated by Django 4.2 on 2023-05-28 09:18

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='category',
            name='favourite',
            field=models.BooleanField(default=False, verbose_name='избраная категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='catalog.category', verbose_name='родитель'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='categoryicon',
            name='src',
            field=models.FileField(max_length=500, upload_to=catalog.models.category_image_directory_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(default=True, verbose_name='бесплатная доставка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(blank=True, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='ограниченая серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=catalog.models.product_image_directory_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(default='', max_length=256, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=128, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='емейл'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(default='', verbose_name='старт продаж'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(blank=True, null=True, verbose_name='окончание продаж'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продукт', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salePrice',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='цена по скидке'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(related_name='tags', to='catalog.product', verbose_name='тэг'),
        ),
    ]
